/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mechanic = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'specialties' : IDL.Vec(IDL.Text),
  'rating' : IDL.Float64,
  'location' : IDL.Text,
});
export const Trip = IDL.Record({
  'to' : IDL.Text,
  'tripType' : IDL.Variant({
    'scenic' : IDL.Null,
    'urban' : IDL.Null,
    'offroad' : IDL.Null,
  }),
  'days' : IDL.Nat,
  'from' : IDL.Text,
  'waypoints' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Group = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'avatar' : IDL.Text,
});
export const FeedPost = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Principal,
});
export const MechanicRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'mechanic' : IDL.Text,
  'problemDescription' : IDL.Text,
});
export const Event = IDL.Record({
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'attendees' : IDL.Vec(IDL.Principal),
  'location' : IDL.Text,
  'datetime' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMechanic' : IDL.Func([Mechanic], [], []),
  'addTrip' : IDL.Func([Trip], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createMechanicRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text], [], []),
  'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(FeedPost)], ['query']),
  'getMechanics' : IDL.Func([], [IDL.Vec(Mechanic)], ['query']),
  'getProfileOverview' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'groups' : IDL.Vec(Group),
          'mechanicRequests' : IDL.Vec(MechanicRequest),
          'events' : IDL.Vec(Event),
          'posts' : IDL.Vec(FeedPost),
          'profile' : IDL.Opt(Profile),
        }),
      ],
      ['query'],
    ),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getUserRequests' : IDL.Func([], [IDL.Vec(MechanicRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinEvent' : IDL.Func([IDL.Nat], [], []),
  'joinGroup' : IDL.Func([IDL.Nat], [], []),
  'leaveEvent' : IDL.Func([IDL.Nat], [], []),
  'leaveGroup' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'suggestTrips' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({
          'scenic' : IDL.Null,
          'urban' : IDL.Null,
          'offroad' : IDL.Null,
        }),
      ],
      [IDL.Vec(Trip)],
      ['query'],
    ),
  'updateRequestStatus' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'rejected' : IDL.Null,
          'accepted' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mechanic = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'specialties' : IDL.Vec(IDL.Text),
    'rating' : IDL.Float64,
    'location' : IDL.Text,
  });
  const Trip = IDL.Record({
    'to' : IDL.Text,
    'tripType' : IDL.Variant({
      'scenic' : IDL.Null,
      'urban' : IDL.Null,
      'offroad' : IDL.Null,
    }),
    'days' : IDL.Nat,
    'from' : IDL.Text,
    'waypoints' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Group = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const FeedPost = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Principal,
  });
  const MechanicRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'mechanic' : IDL.Text,
    'problemDescription' : IDL.Text,
  });
  const Event = IDL.Record({
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'attendees' : IDL.Vec(IDL.Principal),
    'location' : IDL.Text,
    'datetime' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMechanic' : IDL.Func([Mechanic], [], []),
    'addTrip' : IDL.Func([Trip], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createMechanicRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text], [], []),
    'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(FeedPost)], ['query']),
    'getMechanics' : IDL.Func([], [IDL.Vec(Mechanic)], ['query']),
    'getProfileOverview' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'groups' : IDL.Vec(Group),
            'mechanicRequests' : IDL.Vec(MechanicRequest),
            'events' : IDL.Vec(Event),
            'posts' : IDL.Vec(FeedPost),
            'profile' : IDL.Opt(Profile),
          }),
        ],
        ['query'],
      ),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getUserRequests' : IDL.Func([], [IDL.Vec(MechanicRequest)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinEvent' : IDL.Func([IDL.Nat], [], []),
    'joinGroup' : IDL.Func([IDL.Nat], [], []),
    'leaveEvent' : IDL.Func([IDL.Nat], [], []),
    'leaveGroup' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'suggestTrips' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({
            'scenic' : IDL.Null,
            'urban' : IDL.Null,
            'offroad' : IDL.Null,
          }),
        ],
        [IDL.Vec(Trip)],
        ['query'],
      ),
    'updateRequestStatus' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'rejected' : IDL.Null,
            'accepted' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };