/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'attendees' : Array<Principal>,
  'location' : string,
  'datetime' : bigint,
}
export interface FeedPost {
  'content' : string,
  'createdAt' : bigint,
  'author' : Principal,
}
export interface Group {
  'members' : Array<Principal>,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface Mechanic {
  'contactInfo' : string,
  'name' : string,
  'specialties' : Array<string>,
  'rating' : number,
  'location' : string,
}
export interface MechanicRequest {
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'createdAt' : bigint,
  'user' : Principal,
  'mechanic' : string,
  'problemDescription' : string,
}
export interface Profile { 'bio' : string, 'name' : string, 'avatar' : string }
export interface Trip {
  'to' : string,
  'tripType' : { 'scenic' : null } |
    { 'urban' : null } |
    { 'offroad' : null },
  'days' : bigint,
  'from' : string,
  'waypoints' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMechanic' : ActorMethod<[Mechanic], undefined>,
  'addTrip' : ActorMethod<[Trip], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<[string, string, string, bigint], undefined>,
  'createGroup' : ActorMethod<[string, string], undefined>,
  'createMechanicRequest' : ActorMethod<[string, string], undefined>,
  'createPost' : ActorMethod<[string], undefined>,
  'getAllGroups' : ActorMethod<[], Array<Group>>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeed' : ActorMethod<[], Array<FeedPost>>,
  'getMechanics' : ActorMethod<[], Array<Mechanic>>,
  'getProfileOverview' : ActorMethod<
    [Principal],
    {
      'groups' : Array<Group>,
      'mechanicRequests' : Array<MechanicRequest>,
      'events' : Array<Event>,
      'posts' : Array<FeedPost>,
      'profile' : [] | [Profile],
    }
  >,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUserRequests' : ActorMethod<[], Array<MechanicRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinEvent' : ActorMethod<[bigint], undefined>,
  'joinGroup' : ActorMethod<[bigint], undefined>,
  'leaveEvent' : ActorMethod<[bigint], undefined>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'suggestTrips' : ActorMethod<
    [
      string,
      string,
      bigint,
      { 'scenic' : null } |
        { 'urban' : null } |
        { 'offroad' : null },
    ],
    Array<Trip>
  >,
  'updateRequestStatus' : ActorMethod<
    [
      Principal,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'rejected' : null } |
        { 'accepted' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];