/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Trip {
    to: string;
    tripType: Variant_scenic_urban_offroad;
    days: bigint;
    from: string;
    waypoints: Array<string>;
}
export interface Event {
    owner: Principal;
    name: string;
    createdAt: bigint;
    description: string;
    attendees: Array<Principal>;
    location: string;
    datetime: bigint;
}
export interface MechanicRequest {
    status: Variant_pending_completed_rejected_accepted;
    createdAt: bigint;
    user: Principal;
    mechanic: string;
    problemDescription: string;
}
export interface Group {
    members: Array<Principal>;
    owner: Principal;
    name: string;
    createdAt: bigint;
    description: string;
}
export interface Profile {
    bio: string;
    name: string;
    avatar: string;
}
export interface Mechanic {
    contactInfo: string;
    name: string;
    specialties: Array<string>;
    rating: number;
    location: string;
}
export interface FeedPost {
    content: string;
    createdAt: bigint;
    author: Principal;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_completed_rejected_accepted {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum Variant_scenic_urban_offroad {
    scenic = "scenic",
    urban = "urban",
    offroad = "offroad"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMechanic(mechanic: Mechanic): Promise<void>;
    addTrip(trip: Trip): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEvent(name: string, location: string, description: string, datetime: bigint): Promise<void>;
    createGroup(name: string, description: string): Promise<void>;
    createMechanicRequest(problemDescription: string, mechanic: string): Promise<void>;
    createPost(content: string): Promise<void>;
    getAllGroups(): Promise<Array<Group>>;
    getAllTrips(): Promise<Array<Trip>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeed(): Promise<Array<FeedPost>>;
    getMechanics(): Promise<Array<Mechanic>>;
    getProfileOverview(user: Principal): Promise<{
        groups: Array<Group>;
        mechanicRequests: Array<MechanicRequest>;
        events: Array<Event>;
        posts: Array<FeedPost>;
        profile?: Profile;
    }>;
    getUpcomingEvents(): Promise<Array<Event>>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    getUserRequests(): Promise<Array<MechanicRequest>>;
    isCallerAdmin(): Promise<boolean>;
    joinEvent(eventId: bigint): Promise<void>;
    joinGroup(groupId: bigint): Promise<void>;
    leaveEvent(eventId: bigint): Promise<void>;
    leaveGroup(groupId: bigint): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    suggestTrips(from: string, to: string, days: bigint, tripType: Variant_scenic_urban_offroad): Promise<Array<Trip>>;
    updateRequestStatus(user: Principal, status: Variant_pending_completed_rejected_accepted): Promise<void>;
}
import type { Event as _Event, FeedPost as _FeedPost, Group as _Group, MechanicRequest as _MechanicRequest, Profile as _Profile, Trip as _Trip, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMechanic(arg0: Mechanic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMechanic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMechanic(arg0);
            return result;
        }
    }
    async addTrip(arg0: Trip): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrip(to_candid_Trip_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrip(to_candid_Trip_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1);
            return result;
        }
    }
    async createMechanicRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMechanicRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMechanicRequest(arg0, arg1);
            return result;
        }
    }
    async createPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0);
            return result;
        }
    }
    async getAllGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroups();
            return result;
        }
    }
    async getAllTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeed(): Promise<Array<FeedPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed();
            return result;
        }
    }
    async getMechanics(): Promise<Array<Mechanic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMechanics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMechanics();
            return result;
        }
    }
    async getProfileOverview(arg0: Principal): Promise<{
        groups: Array<Group>;
        mechanicRequests: Array<MechanicRequest>;
        events: Array<Event>;
        posts: Array<FeedPost>;
        profile?: Profile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileOverview(arg0);
                return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileOverview(arg0);
            return from_candid_record_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRequests(): Promise<Array<MechanicRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinEvent(arg0);
            return result;
        }
    }
    async joinGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGroup(arg0);
            return result;
        }
    }
    async leaveEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveEvent(arg0);
            return result;
        }
    }
    async leaveGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async suggestTrips(arg0: string, arg1: string, arg2: bigint, arg3: Variant_scenic_urban_offroad): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.suggestTrips(arg0, arg1, arg2, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suggestTrips(arg0, arg1, arg2, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRequestStatus(arg0: Principal, arg1: Variant_pending_completed_rejected_accepted): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_MechanicRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MechanicRequest): MechanicRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    groups: Array<_Group>;
    mechanicRequests: Array<_MechanicRequest>;
    events: Array<_Event>;
    posts: Array<_FeedPost>;
    profile: [] | [_Profile];
}): {
    groups: Array<Group>;
    mechanicRequests: Array<MechanicRequest>;
    events: Array<Event>;
    posts: Array<FeedPost>;
    profile?: Profile;
} {
    return {
        groups: value.groups,
        mechanicRequests: from_candid_vec_n14(_uploadFile, _downloadFile, value.mechanicRequests),
        events: value.events,
        posts: value.posts,
        profile: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        rejected: null;
    } | {
        accepted: null;
    };
    createdAt: bigint;
    user: Principal;
    mechanic: string;
    problemDescription: string;
}): {
    status: Variant_pending_completed_rejected_accepted;
    createdAt: bigint;
    user: Principal;
    mechanic: string;
    problemDescription: string;
} {
    return {
        status: from_candid_variant_n17(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        user: value.user,
        mechanic: value.mechanic,
        problemDescription: value.problemDescription
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: string;
    tripType: {
        scenic: null;
    } | {
        urban: null;
    } | {
        offroad: null;
    };
    days: bigint;
    from: string;
    waypoints: Array<string>;
}): {
    to: string;
    tripType: Variant_scenic_urban_offroad;
    days: bigint;
    from: string;
    waypoints: Array<string>;
} {
    return {
        to: value.to,
        tripType: from_candid_variant_n9(_uploadFile, _downloadFile, value.tripType),
        days: value.days,
        from: value.from,
        waypoints: value.waypoints
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): Variant_pending_completed_rejected_accepted {
    return "pending" in value ? Variant_pending_completed_rejected_accepted.pending : "completed" in value ? Variant_pending_completed_rejected_accepted.completed : "rejected" in value ? Variant_pending_completed_rejected_accepted.rejected : "accepted" in value ? Variant_pending_completed_rejected_accepted.accepted : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scenic: null;
} | {
    urban: null;
} | {
    offroad: null;
}): Variant_scenic_urban_offroad {
    return "scenic" in value ? Variant_scenic_urban_offroad.scenic : "urban" in value ? Variant_scenic_urban_offroad.urban : "offroad" in value ? Variant_scenic_urban_offroad.offroad : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MechanicRequest>): Array<MechanicRequest> {
    return value.map((x)=>from_candid_MechanicRequest_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Trip_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trip): _Trip {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: string;
    tripType: Variant_scenic_urban_offroad;
    days: bigint;
    from: string;
    waypoints: Array<string>;
}): {
    to: string;
    tripType: {
        scenic: null;
    } | {
        urban: null;
    } | {
        offroad: null;
    };
    days: bigint;
    from: string;
    waypoints: Array<string>;
} {
    return {
        to: value.to,
        tripType: to_candid_variant_n3(_uploadFile, _downloadFile, value.tripType),
        days: value.days,
        from: value.from,
        waypoints: value.waypoints
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_rejected_accepted): {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == Variant_pending_completed_rejected_accepted.pending ? {
        pending: null
    } : value == Variant_pending_completed_rejected_accepted.completed ? {
        completed: null
    } : value == Variant_pending_completed_rejected_accepted.rejected ? {
        rejected: null
    } : value == Variant_pending_completed_rejected_accepted.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_scenic_urban_offroad): {
    scenic: null;
} | {
    urban: null;
} | {
    offroad: null;
} {
    return value == Variant_scenic_urban_offroad.scenic ? {
        scenic: null
    } : value == Variant_scenic_urban_offroad.urban ? {
        urban: null
    } : value == Variant_scenic_urban_offroad.offroad ? {
        offroad: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
